import type { Portfolio } from "@/db/schema";

// Dummy data for demo preview
export const dummyPortfolio: Partial<Portfolio> = {
  fullName: "Aayush Kashyap",
  title: "Software Engineer",
  tagline:
    "Specializing in full-stack web development, cloud deployment, and AI-driven automation.",
  bio: "Software engineer skilled in React, Next.js, and TypeScript, focused on building scalable, production-ready products. I love solving problems, taking ownership end-to-end, and working in fast-paced, product-driven teams.",
  skills: [
    "Javascript",
    "React.js",
    "Next.js",
    "Typescript",
    "Node.js",
    "Express.js",
    "Python",
    "C++",
    "AWS",
    "Postgres",
    "TailwindCSS",
    "MongoDB",
    "Docker",
    "Socket.io",
    "Prisma ORM",
    "Hono",
    "Cloudflare Workers",
    "Git",
    "GitHub",
    "Zustand",
    "Websockets",
    "WebRTC",
  ],
  socialLinks: {
    github: "https://github.com/AayushKP",
    linkedin: "https://linkedin.com/in/ayush-kashyap-240655257",
    email: "kashyaapayush26@gmail.com",
    twitter: "https://x.com/aayuk_5183",
    resume: "https://drive.google.com/file/d/1oRbgMiDWLJdVpa8Ne26X6wXhcHPqukOO",
  },
  experience: [
    {
      id: "1",
      company: "Optimence",
      position: "SDE Intern",
      duration: "Oct'25 - Nov'25",
      description:
        "Built and enhanced features for Transformik.com using Next.js, Supabase, and TypeScript, including AI tools like a content repurposer, a Google Calendar–integrated content manager etc. Also automated workflows with Python for tool listing, dataset handling, controlled extraction, and LLM-based content generation, while maintaining structured tool records for smooth platform operations.",
    },
    {
      id: "2",
      company: "Edunet Foundation",
      position: "AI & Cloud Intern",
      duration: "July'25 - Aug'25",
      description:
        "Worked on an Agentic AI project on IBM Cloud, integrating Retrieval-Augmented Generation (RAG) with foundation models to solve digital financial literacy problem.",
    },
    {
      id: "3",
      company: "Heritage Institute of Technology",
      position: "Freelance Engineer",
      duration: "June'25 - July'25",
      description:
        "Designed and developed the official Resonance Music Club website with Next.js, Tailwind, Canvas-based dynamic background, and shadcn-UI. Integrated Cloudinary and Next.js for optimized media storage and image performance..",
    },
  ],
  education: [
    {
      id: "1",
      institution: "Heritage Institute of Technology",
      degree: "B.Tech in CSE(IOT)",
      duration: "2022 - 2026",
      description: "",
    },
    {
      id: "2",
      institution: "Vidya Bhawan Balika Vidyapith",
      degree: "Higher Secondary Education (Class 12th)",
      duration: "2021 - 2022",
      description: "",
    },
  ],
  projects: [
    {
      id: "1",
      title: "P2P File Sharing System",
      description:
        "Browser-based peer-to-peer file sharing using WebRTC DataChannels, with WebSockets limited to signaling and optimized chunked streaming for large files",
      tags: ["React", "WebRTC", "WebSockets", "Node.js", "TailwindCSS"],
      live: "https://p2p-sharing.vercel.app",
      github: "https://github.com/AayushKP/p2p-sharing",
      image: "",
      featured: true,
    },
    {
      id: "2",
      title: "ComuniQ",
      description:
        "ComuniQ is a real-time chat application crafted for seamless communication through direct messages and group channels.",
      tags: [
        "React",
        "Tailwind",
        "Zustand",
        "Node.js",
        "Express",
        "Multer",
        "MongoDB",
        "Socket.io",
        "Cloudinary",
        "AWS",
        "NGINX",
      ],
      live: "https://chat-comuniq.vercel.app",
      github: "https://github.com/AayushKP/ComuniQ",
      image: "",
      featured: true,
    },
    {
      id: "3",
      title: "Postly",
      description:
        "Postly is a scalable cloud-based blog platform built with Hono.js, Cloudflare Workers, React, and TypeScript, offering serverless performance.",
      tags: [
        "React",
        "Tailwind",
        "Typescript",
        "Hono.js",
        "Prisma",
        "PostgresSQL",
        "Mistral AI",
        "Langchain",
        "Cloudinary",
        "Cloudflare Workers",
      ],
      live: "https://postly-delta.vercel.app",
      github: "https://github.com/AayushKP/Postly",
      image: "",
      featured: true,
    },
    {
      id: "4",
      title: "Resonance",
      description:
        "The Resonance Music Club official website is an immersive digital platform crafted for showcasing musical events and achievements with a dynamic Canvas background and optimized media delivery.",
      tags: [
        "Next.js",
        "Typescript",
        "TailwindCSS",
        "Shadcn UI",
        "Magic UI",
        "Framer-Motion",
        "Cloudinary",
      ],
      live: "https://resonance-hitk.com",
      github: "https://github.com/AayushKP/Resonance",
      image: "",
      featured: true,
    },
    {
      id: "5",
      title: "LinkedIn Clone",
      description:
        "A functional LinkedIn clone featuring a posts system and other key UI components of LinkedIn. Utilizes Firebase for authentication and Redux.js for state management.",
      tags: ["React.js", "TailwindCSS", "Shadcn UI"],
      live: "https://linkedin-clone-ae2e5.web.app",
      github: "https://github.com/AayushKP/linkedIn-clone-Frontend-",
      image: "",
      featured: false,
    },
    {
      id: "6",
      title: "Planify",
      description:
        "A clean and responsive landing page built using React.js and Tailwind CSS, designed with a modern UI/UX focus.",
      tags: ["React.js", "Typescript", "TailwindCSS"],
      live: "https://planify-landing-page-three.vercel.app",
      image: "",
      featured: false,
    },
    {
      id: "7",
      title: "Velvet Bean",
      description:
        "Velvet Bean is an immersive, editorial-style landing page for an artisanal coffee roastery, featuring advanced scroll-driven animations and parallax effects.",
      tags: ["React.js", "Typescript", "TailwindCSS"],
      live: "https://coffee-landing-page-blond.vercel.app",
      image: "",
      featured: false,
    },
    {
      id: "8",
      title: "Noir : The Nighligfe Experience",
      description:
        "A cinematic luxury nightclub landing page featuring neon-glow visuals, immersive animations, and premium nightlife interactions.",
      tags: ["React.js", "Typescript", "TailwindCSS"],
      live: "https://noir-landing-page.vercel.app",
      image: "",
      featured: false,
    },
    {
      id: "9",
      title: "Creatorise",
      description:
        "Creatorise is a multi-page, fully responsive landing page for a fictional creative platform, built with React and Tailwind CSS.",
      tags: ["React.js", "Typescript", "TailwindCSS"],
      live: "https://creatorise-landing-repo.vercel.app",
      image: "",
      featured: false,
    },
  ],
  blogs: [
    {
      id: "1",
      title: "How the Javascript Engine Works",
      description: "Read more ...",
      link: "https://medium.com/@kashyaap.a/how-the-javascript-engine-works-c56e9536d808",
      date: "2025",
    },
    {
      id: "2",
      title: "Behind the Scenes of Javascript Asynchronous Magic",
      description: "Read more ...",
      link: "https://medium.com/@kashyaap.a/behind-the-scenes-of-javascript-asynchronous-magic-b257a74c5bb5",
      date: "2025",
    },
    {
      id: "3",
      title: "Making My App Faster and Scalable: What I Learned About Redis",
      description: "Read more ...",
      link: "https://medium.com/@kashyaap.a/making-my-app-faster-and-scalable-what-i-learned-about-redis-ac1256b8a68f",
      date: "2026",
    },
  ],
};
